name: Build

on:
  push:
    branches:
      - 'main'
      - 'v*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: package
        working-directory: dist/directory-browser
        run: zip -qq -r ../../directory-browser.zip .
      - uses: actions/upload-artifact@v2
        with:
          name: directory-browser
          path: directory-browser.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: directory-browser.zip



